version: '3'

services:
  dev_pgsql:
    container_name: dev_pgsql
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=hello_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  dev_redis:
    container_name: dev_redis
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=passw0rd
    ports:
      - '6379:6379'