version: '3'

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

services:
  dev_pgsql:
    container_name: dev_pgsql
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=hello_api_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - dev_hello_api

  # dev_redis:
  #   container_name: dev_redis
  #   image: bitnami/redis:latest
  #   environment:
  #     - REDIS_PASSWORD=passw0rd
  #   ports:
  #     - '6379:6379'
  #   networks:
  #     - dev_hello_api
  
  # dev_zookeeper:
  #   container_name: dev_zookeeper
  #   image: 'bitnami/zookeeper:latest'
  #   ports:
  #     - '2181:2181'
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #   # volumes:
  #   #   - zookeeper_data:/bitnami/zookeeper
  #   networks:
  #     - dev_hello_api
  # dev_kafka1:
  #   container_name: dev_kafka1
  #   image: 'bitnami/kafka:latest'
  #   ports:
  #     - '9091:9092'
  #   # volumes:
  #   #   - 'kafka_data:/bitnami/kafka'
  #   environment:
  #     # - KAFKA_PORT_NUMBER=9092
  #     - KAFKA_ZOOKEEPER_CONNECT=dev_zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   depends_on:
  #     - dev_zookeeper
  #   links:
  #     - dev_zookeeper
  #   networks:
  #     - dev_hello_api
  # dev_kafka2:
  #   container_name: dev_kafka2
  #   image: 'bitnami/kafka:latest'
  #   ports:
  #     - '9092:9092'
  #   environment:
  #     - KAFKA_ZOOKEEPER_CONNECT=dev_zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   depends_on:
  #     - dev_zookeeper
  #   links:
  #     - dev_zookeeper
  #   networks:
  #     - dev_hello_api
  # dev_kafka3:
  #   container_name: dev_kafka3
  #   image: 'bitnami/kafka:latest'
  #   ports:
  #     - '9093:9092'
  #   environment:
  #     - KAFKA_ZOOKEEPER_CONNECT=dev_zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   depends_on:
  #     - dev_zookeeper
  #   links:
  #     - dev_zookeeper
  #   networks:
  #     - dev_hello_api

networks:
  dev_hello_api: